Feature/Added ability to log messages format k=v
funbox/loggun pull request #19
Opened 2020-06-01 15:21 UTC by artemnvkv

2020-06-01 17:07 UTC, QNester requested changes

2020-06-01 17:07 UTC, QNester commented on lib/loggun/config.rb
> +      json_format: true,
я бы наверное вместо булевого флага сделал бы whitelist значений
в перспективе мы захотим добавить больше форматов и это будет легко расширить

то есть надо будет указать не `config.json_format = true`, а `config.message_format = :json`

2020-06-01 17:07 UTC, QNester commented on lib/loggun/formatter.rb
> +        message = if config.json_format
давай выделим отдельный метод, типа "format_message" и вынесем туда формирование нужного значения

2020-06-02 07:54 UTC, QNester requested changes

2020-06-02 07:54 UTC, QNester commented on lib/loggun/formatter.rb
> +      end
`else?`

ведь сейчас ничто не мешает передать левое значение, и потребители гема никак об этом не узнают, пока не увидят пустые логи

Как вариант сделать проверку значений на уровне конфига, если передадут что-то левое - рейсить ошибку, это наверное будет лучшим решением

2020-06-02 07:55 UTC, QNester commented on lib/loggun/formatter.rb
> +      end
но можно сделать просто
```
else
  JSON.generate(message_format)
```
то есть формат JSON считаем дефолтным

2020-06-02 09:35 UTC, QNester requested changes

2020-06-02 09:35 UTC, QNester commented on lib/loggun/config.rb
> +        return if %i[json key_value].include? instance.message_format
массив в константу

2020-06-02 09:35 UTC, QNester commented on lib/loggun/formatter.rb
> +        raise FailureConfiguration, 'Unknown value for message_format'
не, здесь лучше просто `JSON.generate(message)` делать + какой-нибудь warn можно оставлять

2020-06-02 09:35 UTC, QNester commented on lib/loggun/config.rb
> +        raise FailureConfiguration, 'Unknown value for message_format'
Если нам пока сложно правильно тестить формат, то такое поведение точно надо протестить здесь https://github.com/funbox/loggun/blob/master/spec/loggun/config_spec.rb

2020-06-02 10:40 UTC, nemestny approved these changes

2020-06-02 10:40 UTC, QNester approved these changes

2020-06-02 13:08 UTC, merged