Improvement/Fix generation json logs
funbox/loggun pull request #28
Opened 2020-09-17 07:09 UTC by artemnvkv

2020-09-17 09:01 UTC, QNester requested changes

2020-09-17 09:01 UTC, QNester commented on lib/loggun/formatter.rb
> +        JSON.generate(message.inspect[1..-2])
Здесь вижу проблему:
На код
```
# initializer
config.pattern = '{ "message": %{message} }'

# code
 Loggun.info("my.best.app", { hello: :world })
```
получаю такое
```
{ "message": ":hello=>:world" }
```
то есть я хочу получить внутри message вложенный JSON, но не выходит

2020-09-17 10:51 UTC, nemestny requested changes
Раз паттерн в случае с json форматом игнорируется, то, как мне кажется, необходимо добавить настройки, позволяющие или исключить некоторые ключи из результата, либо вывести туда только определённые ключи.
Плюс необходимо описать изменения конфигурации в README.
Ну и мне не нравится значение **:custom** в качестве дефолтного значения, описывающего формат лога как текст.

2020-09-17 10:51 UTC, nemestny commented on lib/loggun/config.rb
> +      log_format: :custom,
Может лучше дефолтным значением сделать **:plain** или **:text**?

2020-09-17 10:58 UTC, artemnvkv commented on lib/loggun/config.rb
> +      log_format: :custom,
Ты предлагаешь добавить настройку, которая будет содержать список ключей. А дальше из [data](https://github.com/funbox/loggun/pull/28/files#diff-30443948dbe1a96803ac12f9f4171ac0R35) выбирать только эти ключи для вывода?

2020-09-17 11:03 UTC, nemestny commented on lib/loggun/config.rb
> +      log_format: :custom,
Я предлагаю добавить две настройки: например **exclude**, которая будет содержать ключи, которые будут исключаться из результата (на случай, когда нужны все ключи, кроме одного-двух)
**only**, содержащую только те ключи, которые будут выбираться и исключаться.
Первая работает только если вторая не задана.

2020-09-18 05:05 UTC, nemestny approved these changes

2020-09-21 15:20 UTC, QNester requested changes

2020-09-21 15:20 UTC, QNester commented on lib/loggun/formatter.rb
>        data[:message] = message.to_s.tr("\r\n", ' ').strip
из-за этой строки получается невалидный json если ты хочешь чтобы message был JSON'ом
```
{
  "timestamp": "2020-09-21T18:08:37.239+03:00",
  "pid": 204778,
  "message": "{:type=>true, :test=>:json_format}",
  "severity": "INFO",
  "tags_text": null,
  "type": "hello.world.type",
  "transaction_id": null
}```

Нужно перенести ```.to_s.tr("\r\n", ' ').strip``` в конец format_message
получится типа такого 
```
def format_message(message)
      formatted_msg = if config.message_format == :json
        JSON.generate(message)
      elsif config.message_format == :key_value
        message.map { |key, value| "#{key}=#{value}" }.join(' ')
      else
        warn('Unknown value for message_format')
        JSON.generate(message)
      end

      formatted_msg.to_s.tr("\r\n", ' ').strip
    end
```

2020-09-22 05:34 UTC, artemnvkv commented on lib/loggun/formatter.rb
>        data[:message] = message.to_s.tr("\r\n", ' ').strip
Так тоже не получится сделать, т.к. если мы передадим в качестве `message` не `Hash`, то у нас метод `format_message` не будет вызван или нас это устраивает?

2020-09-22 08:52 UTC, QNester approved these changes

2020-09-22 08:52 UTC, merged